### python libraries
numpy

Travis Oliphant

In [6]:
# Create 1D array
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
type(x)

numpy.ndarray

In [7]:
#create 2D array
import numpy as np
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [8]:
#create 3D array
import numpy as np
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
a=[[1,2,3],[4,5,6],[7,8,9]]
z=np.array(a)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
z[0]

array([1, 2, 3])

In [11]:
z[0][1]

2

In [12]:
y[0]

array([1, 2, 3])

In [13]:
z.shape

(3, 3)

In [14]:
z.size

9

In [15]:
s=np.array([1,2,3,4,5,6],dtype=complex)
print(s)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


**Array Slicing**

In [19]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[5:]

array([5, 6, 7, 8, 9])

In [21]:
x[::2]

array([0, 2, 4, 6, 8])

In [22]:
x[0::2]

array([0, 2, 4, 6, 8])

In [23]:
x[0:9:2]

array([0, 2, 4, 6, 8])

In [24]:
x[1:7:2]

array([1, 3, 5])

In [26]:
n=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(n)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [27]:
s=np.arange(1,10).reshape((3,3))
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


***Concatenation of Arrays***

In [30]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate([x,y])
print(z)

[1 2 3 4 5 6]


In [32]:
z[2]+z[5]

9

**Splitting Arrays**

In [33]:
x=[1,2,3,4,5,6,7,8]
x1,x2,x3=np.split(x,[2,5])
print(x1,x2,x3)

[1 2] [3 4 5] [6 7 8]


In [34]:
a1=np.arange(10000)
a1

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [35]:
a1=np.arange(10000).reshape(100,100)
a1

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [36]:
a2=np.arange(49).reshape(7,7)
a2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [38]:
a2=np.arange(12).reshape(2,6)
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [39]:
s1=np.ones((3,3))
print(s1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [40]:
s2=s1+2
print(s2)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [41]:
s3=s1-2
print(s1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
x=np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
print(np.sqrt(s2))

[[1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]]


In [45]:
print(np.sin(s2))

[[0.14112001 0.14112001 0.14112001]
 [0.14112001 0.14112001 0.14112001]
 [0.14112001 0.14112001 0.14112001]]


In [ ]:
x=np.random.